DefaultContentLanguage: en
defaultContentLanguageInSubdir: true
sitemap:
  filename: sitemap.xml
markup:
  goldmark:
    renderer:
      unsafe: true   
languages:
  en:
    baseUrl: https://digital.canada.ca/
    params:
      home: "content/en/products/_index.html"
    contentDir: content/en
    lang: en
    languageName: English
    title: Blog
    Paginate: 6
    frontmatter:
      date: [":filename", ":default"]
    permalinks:
      blog: /:year/:month/:day/:filename
      work-with-us: /:title
    weight: 1
    menu:
      main:
        - identifier: Products
          name: Products
          url: /
          weight: 1
        - identifier: About CDS
          name: About CDS
          url: /about-us/  
          weight: 2
        - identifier: blog
          name: Blog
          url: /blog/
          weight: 3     
  fr:
    baseUrl: https://numerique.canada.ca/
    contentDir: content/fr
    lang: fr
    languageName: Francais
    title: Blogue
    Paginate: 6
    weight: 2
    frontmatter:
      date: [":filename", ":default"]
    permalinks:
      blog: /:year/:month/:day/:filename
      work-with-us: /:title
    menu:
      main:
        - identifier: Produits
          name: Produits
          url: /
          weight: 1
        - identifier: À propos du SNC
          name: À propos du SNC
          url: /a-propos-du-snc/
          weight: 2  
        - identifier: blogue
          name: Blogue
          url: /blogue/
          weight: 3      
outputs:
  home : [HTML, RSS, JSON]
  page : HTML         
