name: Build-Push

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Load git submodules
      run: git submodule sync && git submodule update --init

    - name: Install hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.124.0/hugo_extended_0.124.0_Linux-64bit.tar.gz \
        && tar -xvf hugo_extended_0.124.0_Linux-64bit.tar.gz hugo \
        && mv  hugo /usr/local/bin \
        && rm hugo_extended_0.124.0_Linux-64bit.tar.gz

    - name: Build english and french sites
      run: |
        hugo --ignoreCache -d ~/cds-website-dist
        chmod -R 755 ~/cds-website-dist

    - name: Cache build
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: |
          ~/cds-website-dist
        key: ${{ runner.os }}-${{ github.sha }}
  
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lang: ["fr", "en"]
    steps:
      - name: Retrieve Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/cds-website-dist
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@5f19ec79cedfadb78ab837f95b87734d0003c899 # v1.173.0
        with:
          ruby-version: 3.0
      - name: install html proofer
        run: gem install html-proofer
      - name: test
        run: |
          htmlproofer ~/cds-website-dist/${{ matrix.lang }} --allow_hash_href --ignore_empty_alt --disable_external --ignore_files=/lib/,/admin/ --checks=favicon  
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - lang: "fr"
            dist-id: "E27JWYHQ4915HY" 
            bucket: "cds-website-french-s3-bucket"
          - lang: "en"
            dist-id: "E3KGR0ME3JJZ19"
            bucket: "cds-website-english-s3-bucket"
    steps:
      - name: Retrieve Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/cds-website-dist
          key: ${{ runner.os }}-${{ github.sha }}
      - name: configure aws credentials using OIDC              
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::521732289257:role/digital-canada-ca-website-apply  # use for TF apply or admin access (only works on `main` branch)
          role-session-name: cache
          aws-region: ca-central-1
      - name: Deploy and invalidate cache
        run: |
          aws s3 sync ~/cds-website-dist/${{ matrix.lang }} s3://${{ matrix.bucket }}/ --delete
          aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"${{ matrix.dist-id}}\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"
      - name: Report deployment to Sentinel
        uses: cds-snc/sentinel-forward-data-action@main
        with:
          input_data: '{"product": "${{ matrix.bucket }}", "version": "${{ github.sha }}", "repository": "${{ github.repository }}", "environment": "production"}'
          log_type: CDS_Product_Deployment_Data
          log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}        