name: "Terraform Apply Production"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/**"
      - ".github/workflows/tf_apply_production.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.4.6
  TERRAGRUNT_VERSION: 0.45.11
  CONFTEST_VERSION: 0.42.1

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write
  
jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: arn:aws:iam::521732289257:role/digital-canada-ca-website-apply  # use for TF apply or admin access (only works on `main` branch)
          role-session-name: TFApply
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Apply S3
        working-directory: terragrunt/env/production/s3
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terraform Apply Cloudfront
        working-directory: terragrunt/env/production/cloudfront
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
      
      - name: Terraform apply ECR
        working-directory: terragrunt/env/production/ecr
        run: terragrunt apply --terragrunt-non-interactive -auto-approve