name: "Terraform Plan"

on:
  workflow_dispatch:
  pull_request:
    paths:
    - "terragrunt/**"
    - ".github/workflows/tf_plan_production.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.4.6
  TERRAGRUNT_VERSION: 0.45.11
  CONFTEST_VERSION: 0.42.1

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: s3
          - module: cloudfront
          - module: ecr 

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: set up terraform tools
      uses: cds-snc/terraform-tools-setup@v1

    - name: configure aws credentials using OIDC
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        role-to-assume: arn:aws:iam::521732289257:role/digital-canada-ca-website-plan   # use for TF plan or when you only need read-only access (works on all branches)
        role-session-name: TFPlan
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Plan
      uses: cds-snc/terraform-plan@4719878d72d1b0078e0bce2e7571e854e79903b8 # v3.2.2
      with:
        comment-delete: true
        comment-title: "Production: ${{ matrix.module }}"
        directory: terragrunt/env/production/${{ matrix.module }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        terragrunt: true   

